import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CoinGecko from "coingecko-api";
const coinGeckoClient = new CoinGecko();

export default function Home(props) {
  const { data } = props.result;

  const formatPercent = (number) => `${new Number(number).toFixed(2)}%`;

  const formatDollar = (number, maxSignificantDigits) =>
    new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "usd",
      maximumSignificantDigits: maxSignificantDigits,
    }).format(number);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coinmarket Cap Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Coinmarket Cap Clone</h1>

      <table className="table">
        <thead>
          <tr>
            <th>Symbol</th>
            <th>24H Change</th>
            <th>Price</th>
            <th>Market Cap</th>
          </tr>
        </thead>
        <tbody>
          {data.map((item, index) => (
            <tr key={index}>
              <td>
                {
                  <img
                    src={item.image}
                    alt={item.name}
                    style={{ width: "25px", height: "25px", marginRight: 10 }}
                  />
                }
                {item.symbol.toUpperCase()}
              </td>
              <td>
                <span
                  className={
                    item.price_change_percentage_24h > 0
                      ? "text-success"
                      : "text-danger"
                  }
                >
                  {formatPercent(item.price_change_percentage_24h)}
                </span>
              </td>

              <td>{formatDollar(item.current_price, 20)}</td>
              <td>{formatDollar(item.market_cap, 12)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export async function getServerSideProps(context) {
  const params = {
    order: CoinGecko.ORDER.MARKET_CAP_DESC,
  };
  const result = await coinGeckoClient.coins.markets({ params });
  return {
    props: {
      result,
    },
  };
}
